### ISSUE TITLE
[2.44] Error on import in Android Studio "Zildo_Data" not defined

### ISSUE THREAD

**Issue by Zeronior** [tchegito/zildo#135]
As "SetUpZildo.md" is outdated, I assumed I can import the project into Android Studio (currently using version 3.1).
But it tells me I should define a Zildo_Data: "Error:ZILDO_DATA should be defined !"

What does that mean?

**Comment by tchegito** [comment]
Hi ! Yes, you guessed that correctly. That tutorial is really old. Now, the environment variable ZILDO_DATA should point to the data folder where all the graphics/music/sound/maps are located.

About Android Studio, I never gave it a try. I still use an old Eclipse for that project (Luna).

**Comment by tchegito** [comment]
I closed because there isn't activity any more on this one, and this was not a real issue with the game.
