### ISSUE TITLE
[Question/improvement] Explain player something at the fight against the dragon.

### ISSUE THREAD

**Issue by ghost** [tchegito/zildo#154]
I don't know anymore when I started playing Zildo. I think it's more than a year ago. First I found the controls where not fit for the mobile phone (5"). Then I played on an old Galaxy Tab with Android 4 (7"). Yeah, I got through everything.
I think I needed about 2 months for that (studying when not playing, of course).
So you can say I'm now completely lost with that stupid dragon since 10 months. And whereas everyone talks about this cool game, nobody wants to provide a solution on how you can defeat the monster. The only thing I manage is dying.
Maybe I would need an even bigger display to finally win against it. But it's an Android game. So it should be supposed to be playable with tiny displays.

**Comment by tchegito** [comment]
Hi Ghost ! Thanks for enjoying the game !

Notice that it's not the best place to talk about this ;) Anyway, about controls, I really think the best way is to use a bluetooth controller. I tried so many things to improve the touchpad feeling and usability, but it's really hard to provide a good experience on such platform, especially with small screen. Personally, I have a Samsung Galaxy S2 as my usual testing phone (don't blame me, I know it's old ;) ) and I confess I'm not succeeding cave of the Flames on a first attempt ! Recently I was thinking about a simple and already done touch way: click on the screen, and hero goes where you click. Maybe I'll do that later ...

About the dragon, I just saw a walkthrough few days ago, by Dravenity here: https://www.youtube.com/watch?v=ecc_Yo3nBZs

You will see how the dragon can be killed, at last ;) Enjoy !
By the way, I don't know this guy at all, and I'm really surprised about the slowness of the video, but he did it ! Thanks to him.

PS: I will close this issue shortly, and we could continue this conversation by email, if you want.
