### ISSUE TITLE
Bluetooth evolution

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#182]
A sympathetic player has asked me about some key customization, to override the default buttons assigned in the game (A,B,X,Y).

Here is a quote from him:
"Then there is the A B X Y buttons. A pulls up items, B brings up menu, X picks up/throws bushes, and Y is sword attack. I would live to be able to remap these to more traditional NES controls. Something like A would be pick up, X sword, Y items, and B menu. It would be awesome if these buttons were remappable in-game."

+ a wierd bug I detected in the "load game" menu. Apparently, player can't use the "down" key. Everything else is okay, so he has to wrap from the up to go down. Not really user-friendly ...

**Comment by tchegito** [comment]
Fixed in 2.62

91e82d95367591244921186260baabce12947bed

**Comment by Alberto1993D** [comment]
Hello!
When is v2.63?
