### ISSUE TITLE
[2.25] [major] screen loading error when navigating on waterlily

### ISSUE THREAD

**Issue by nashounet** [tchegito/zildo#96]
The game sometimes start to act really weird when I cross the screen coming back from Fishermen's Island.
It seems to occur mainly when I spam sword swings while changing screens.

The game can't place me on the arriving screen and start to flicker between to screens.
It sometimes stay stucked flicking, and sometimes it places me randomly on the first map.

**Comment by tchegito** [comment]
Fixed in [2.29].

a7185653e204eba5859362a7eb5e20b0661be9fe
