### ISSUE TITLE
[2.25] [minor] bushes won't disappear after being picked up

### ISSUE THREAD

**Issue by nashounet** [tchegito/zildo#97]
This one is hard to reproduce.
Randomly, when plucking bushes, the original tile won't change, leaving a bush on the ground while I'm holding one.
The bush is walkable as if the stump tile was shown.
I found it happened more frequently in the long patch of bushes near the tavern of Lugdunia.

**Comment by tchegito** [comment]
I already saw that, but a concrete test case would be nice. For example, a precise map and bushes location.

About the cause, it's due to graphic optimization.

**Comment by tchegito** [comment]
Fixed in [2.29]

a969b3fb3be1c2c7dc3663347e4328c2c41b835f
